int verificarCPF(char*);
int verificarnome(char*);
int verificarfone(char*);
int verificaremail(char*);
int verificarnumero(char*);
int verificarletra(char);
int verificarpreco(char*);
char* duplica(char*);
char* lelinha(void);